### ISSUE TITLE
Vložení videa do webu

### ISSUE THREAD

**Issue by Hody586** [nepoveda/enofca#12]
Zapnout video na webu.  Jako další bod viz obrázek. Video je na Youtube. Na webu stačí menší kvalita a bez zvuku. Snad to nějak půjde. 

Video zde. https://www.youtube.com/watch?v=SFIlhSFZ_lk

![image](https://user-images.githubusercontent.com/45258278/51789042-26fd1d00-2185-11e9-9759-49039f9d3ad7.png)

**Comment by nepoveda** [comment]
co bude na pozadí u tohoto slidu s videem?
