### ISSUE TITLE
Disclaimer při vtupu na stránku místo dosavadního

### ISSUE THREAD

**Issue by Hody586** [nepoveda/enofca#14]
Současný disclaimer omezuje vstup uživatelů od 18 let. V některých zemích jsou to povoleny jiné roky proto je třeba to zobecnit na větu "Due to the content of this website, you must be age of majority in your jurisdiction. Are you of legal age?" Yes    No   
Asi takto

![image](https://user-images.githubusercontent.com/45258278/51789220-d8508280-2186-11e9-9a16-9eaad77d22f6.png)

**Comment by nepoveda** [comment]
změnil jsem text... uvidíme co s tím dál :)
