### ISSUE TITLE
Logo v rohu stránky

### ISSUE THREAD

**Issue by Hody586** [nepoveda/enofca#16]
Tak jak je na homepage nalevo v rohu logo ENOFCA, tak toto logo umístit v celém webu tak, aby když budu třeba ve strainech, tak na toto logo kliknu a vrátí mne to na homepage. 
Nebo jsme se bavili v hospodě, že by navigační bar sjížděl jak člověk roluje sránkou. Snad si pamatuješ. Nechám na tobě jakou variantu vyberes :-) 

![image](https://user-images.githubusercontent.com/45258278/51789373-84469d80-2188-11e9-970c-8ac4b7889639.png)

**Comment by nepoveda** [comment]
Použiji na to navbar... současné menu půjde horizontálně a navrh stránky, na mobilu nebo tak se zredukuje na něcojako je naše současné tlačítko + logo...

přikládám obrázky mobil + desktop s tím že místo Brand bude logo

desktop:
![desktop-nav](https://user-images.githubusercontent.com/17991830/52181968-5bfa1700-27f8-11e9-811a-415e79284909.png)

mobil (po kliknutí se menu rozvine do podoby, jak ho máme dnes):
![mobile-nav](https://user-images.githubusercontent.com/17991830/52181969-5bfa1700-27f8-11e9-9213-cb692231deeb.png)

**Comment by nepoveda** [comment]
samozřejmně se to jinak obarví a dostyluje

**Comment by nepoveda** [comment]
https://getbootstrap.com/docs/3.3/components/#navbar-fixed-top

**Comment by nepoveda** [comment]
prosil bych aktuální logo nejlépe v svg (nebo jiných vektorech)....
případně šlo by mu udělat transparentní pozadí?
