### ISSUE TITLE
Pocitové tabulky

### ISSUE THREAD

**Issue by Hody586** [nepoveda/enofca#3]
Seřadit u jednotlivých sekcí: medicinal, effects a negatives od nejvyšší hodnoty po nejnižsí, aby to nebylo tak rozházené. viz leafly.com  
![image](https://user-images.githubusercontent.com/45258278/48894720-b7487a00-ee43-11e8-823f-d496c648885e.png)

**Comment by nepoveda** [comment]
v současném provedení takřka neproveditelné... Po přepsání už to bude brnkačka..
