### ISSUE TITLE
Shození eshopu

### ISSUE THREAD

**Issue by Hody586** [nepoveda/enofca#4]
Ahoj Dane. 
S Tomášem jsme se rozhodli, že by se prozatím shodil eshop na webu. Prostě, aby člověk co přejde na enofca.com, aby neviděl záložku eshop. Doteď je zbytečné, aby to tam bylo, když nemáme platbu kartou. Dále nám to brání o vyjednávání s cenou. Šlo by to nějak udělat prosím? Eshop externě prostě bude pořád někde funkční, ale aby prostě člověk z enofca.com nemohl nic koupit. Díky moc

**Comment by Ellrey** [comment]
Dal by bylo fajn nejak vymyslet to nase reseni,at to muzeme pak co nejdrive uvest zase do chodu. Asi k tomu Danigu napis moznosti a od toho se odrazime dal...
